funds_info/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views

app_name = "funds_info"
urlpatterns = [
    url(r'^$', views.show_funds_list, name='show_funds_list'),
    #url(r'^fund/$', views.show_funds_list, name='show_funds_list'),
    url(r'^fund/nav_change/', views.get_nav_change, name='get_nav_change'),    
    url(r'^fund/(?P<page_slug>[\w-]+)/', views.show_all_stocks, name='show_all_stocks'),
]

nav_analyzer/urls.py
from django.views.generic import RedirectView
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from core import views as core_views
from authentication import views as nav_analyzer_auth_views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url = '/funds/')),
    url(r'^funds/', include('funds_info.urls')),
]

core/models.py
from django.db import models

# Create your models here.

funds_info/models.py
from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.
class Fund(models.Model):
    fund_name = models.CharField(max_length=200)
    stock_name = models.CharField(max_length=300)
    slug_url = models.SlugField(default="update_me")
    stock_allocation = models.FloatField(default=0.0)
    cash_allocation = models.FloatField(default=0.0)

    def save(self, *args, **kwargs):
        self.slug_url = slugify(self.fund_name)
        super(Fund, self).save(*args, **kwargs)
    
class Stock(models.Model):
    stock_name = models.CharField(max_length=300)    
    stock_code = models.CharField(max_length=50)

core/views.py
from django.shortcuts import render

def home(request):
    #if request.user.is_authenticated():
    return render(request, "core/welcome.html")

funds_info/views.py
import json

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.db import connection
from .models import Fund, Stock
from . import nav_change

def show_funds_list(request):
    funds_data = {}

    distinct_funds = Fund.objects.order_by().values_list('fund_name').distinct()
    funds_list = []

    if distinct_funds:
        for fund in distinct_funds:
            fund = ''.join(fund)
            fund_object = Fund.objects.filter(fund_name=fund)[:1]
            slug = fund_object[0].slug_url
            data = {}
            data["fund"] = fund
            data["slug"] = slug
            funds_list.append(data)

    funds_data["funds_list"] = funds_list

    context = {
        'funds_data': funds_data
    }

    return render(request, "funds_info/welcome.html", context)

## View to show all stocks held by a fund
def show_all_stocks(request, page_slug):    
    #print("page_slug: ", page_slug)
    objects = Fund.objects.filter(slug_url=page_slug)
    stocks_list = []
    for obj in objects:
        stock = obj.stock_name
        stocks_list.append(stock)

    #print(stocks_list)

    context = {
        'fund_data': objects,
        'slug': objects[0].slug_url
    }
    return render(request, "funds_info/show_all_stocks.html", context)

def get_nav_change(request):
    fund_slug = request.GET.get('list')

    rows = my_custom_sql(fund_slug)
    mf_nav_change = nav_change.MutualFundNavAnalysis()
    total_change = mf_nav_change.get_nav_change(rows)
    total_change = str(total_change)

    if total_change[0] != '-':
        total_change = "+" + total_change

    return JsonResponse({"ch": total_change})
    
def my_custom_sql(fund_slug):
    cursor = connection.cursor()    
    cursor.execute("""select funds_info_fund.stock_name, stock_allocation, stock_code 
                    from funds_info_fund join funds_info_stock 
                    on funds_info_fund.stock_name = funds_info_stock.stock_name 
                    where slug_url='"""+ fund_slug +"""';""")
    rows = cursor.fetchall()

    return rows

core/templates/core/cover.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
  <link href="{% static 'css/cover.css' %}" rel="stylesheet">
{% endblock head %}

{% block body %}
  <a href="https://github.com/vitorfs/bootcamp"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/e7bbb0521b397edbd5fe43e7f760759336b5e05f/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677265656e5f3030373230302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png"></a>
  <div>
    <h1 class="logo">Bootcamp</h1>
    {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{ error }}
        </div>
      {% endfor %}
    {% endif %}
    <div class="login">
      <h2>{% trans 'Log in' %}</h2>
      <form method="post" action="{% url 'login' %}" role="form">
        {% csrf_token %}
        <div class="form-group{% if form.username.errors %} has-error{% endif %}">
          <label for="username">{% trans 'Username' %}</label>
          <input type="text" class="form-control" id="username" name="username">
          {% for error in form.username.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
        <div class="form-group{% if form.password.errors %} has-error{% endif %}">
          <label for="password">{% trans 'Password' %}</label>
          <input type="password" class="form-control" id="password" name="password">
          {% for error in form.password.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-default">{% trans 'Log in' %}</button>
          <a href="{% url 'signup' %}" class="btn btn-link">{% trans 'Sign up for Bootcamp' %}</a>
        </div>
      </form>
    </div>
  </div>
{% endblock body %}

core/templates/core/welcome.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
  <link href="{% static 'css/welcome.css' %}" rel="stylesheet">
{% endblock head %}

{% block body %}
  <div>
    <h1 class="logo">MF NAV Analyzer</h1>
    {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{ error }}
        </div>
      {% endfor %}
    {% endif %}
    <div class="login">
      <h3>Welcome to Mutual Fund NAV analyzer. Select a fund name whose change in NAV you want to see.</h3>
        <a href="">SBI Bluechip</a>
        <a href="">Mirae Asset India Opportunities</a>
    </div>
  </div>
{% endblock body %}

funds_info/templates/funds_info/show_all_stocks.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
  <link href="{% static 'css/show_all_stocks.css' %}" rel="stylesheet">
  <script src="{% static 'js/nav_change.js' %}" type="text/javascript"></script>
{% endblock head %}

{% block body %}
  <div id="expected-wrapper">
    <span id="nav-change-wrapper" data-attr="{{ slug }}">Get Expected NAV change</span>
    <span id="result"></span>
  </div>
  <ul id="stocks-data-wrapper">
      <li class="st-li first">
        <span class="st-name-title">Stock Name</span>
        <span class="st-wt-title">Weighting</span>            
      </li>
      {% for fund in fund_data %}
          <li class="st-li">
            <span class="st-name">{{ fund.stock_name }}</span>
            <span class="st-wt">{{ fund.stock_allocation }}</span>
          </li>
      {% endfor %}
  </ul>
{% endblock body %}

funds_info/templates/funds_info/welcome.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
  <link href="{% static 'css/welcome.css' %}" rel="stylesheet">
  <link href="{% static 'css/show_all_stocks.css' %}" rel="stylesheet">
{% endblock head %}

{% block body %}
  <div>
    <h1 class="logo">MF NAV Analyzer</h1>
    <div class="heading">
      <h2><span class="title">Welcome to Mutual Fund NAV analyzer</span></h2>
          <h3>As the name suggests, we show the expected change in NAV of a mutual fund for the current day and current time<br>
          based on the stock holdings of the fund. Cash allocation is ignored, assuming it won't amount to much variation in the NAV 
          (this is debatable of course, but we will go ahead with this assumption).
          <br><br>
          Select a fund name whose change in NAV you want to see:</h3>
      {% for fund in funds_data.funds_list %}
          <a href="{% url 'funds_info:show_all_stocks' fund.slug %}">{{ fund.fund }}</a><br>
      {% endfor %}
    </div>
  </div>
{% endblock body %}

nav_analyzer/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Bootcamp{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/bootcamp.css' %}?v=1" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="{% static 'js/bootcamp.js' %}"></script>
    {% block head %}{% endblock %}
  </head>
  <body>
    {% block body %}
      <header>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'home' %}">Bootcamp</a>
            </div>
            <div class="collapse navbar-collapse" id="menu">
              <ul class="nav navbar-nav">
                <li>
                  <a href="#" id="notifications" data-container="body" data-toggle="popover" data-placement="bottom" title="Notifications">
                    <span class="glyphicon glyphicon-bell"></span>
                  </a>
                </li>
                <!--
                <li><a href="{% url 'feeds' %}">{% trans 'Feed' %}</a></li>
                <li><a href="{% url 'articles' %}">{% trans 'Articles' %}</a></li>
                <li><a href="{% url 'questions' %}">{% trans 'Q&A' %}</a></li>
                <li><a href="{% url 'network' %}">{% trans 'Network' %}</a></li>
                -->
              </ul>
              {% if not hide_search %}
                <form class="navbar-form navbar-left" role="search" action="{% url 'search' %}">
                  <div class="input-group" style="width:210px">
                    <input type="text" class="form-control" name="q" placeholder="Search">
                    <span class="input-group-btn">
                      <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                    </span>
                  </div>
                </form>
              {% endif %}
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <a href="{% url 'profile' user.username %}">{{ user.profile.get_screen_name }}</a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'inbox' %}"><span class="badge pull-right" id="unread-count">0</span> Inbox</a></li>
                    <li><a href="{% url 'settings' %}">{% trans 'Account Settings' %}</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'logout' %}">{% trans 'Log out' %}</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <main>
        <div class="container">
          {% block main %}
          {% endblock main %}
        </div>
      </main>
      <script src="{% static 'js/notifications.js' %}"></script>
      <script src="{% static 'js/check_messages.js' %}"></script>
    {% endblock body %}
    <script src="{% static 'js/ga.js' %}"></script>
  </body>
</html>